version: '3.8'

services:
  db:
    image: postgres:15
    container_name: openalex_db
    restart: always
    environment:
      POSTGRES_DB: openalex
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python:
    image: python:3.10
    container_name: openalex_python
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null  # Keeps the container running
    environment:
      DB_HOST: db
      DB_NAME: openalex
      DB_USER: user
      DB_PASSWORD: password

volumes:
  postgres_data: